### ISSUE TITLE
Module parameters missing

### ISSUE THREAD

**Issue by jctull** [NaturalGIS/postgis_geoprocessing#1]
I tried installing this on my OS X system with QGIS trunk code (2.9). The plugin installer reports the plugin is broken, Python said" No module named parameters.

Couldn't load plugin 'postgis_geoprocessing' from ['/Users/jctull/.qgis2/python/plugins/sextante_animove', '/Users/jctull/.qgis2/python/plugins/QSDM', '/Users/jctull/.qgis2/python/plugins/processing', '/Users/jctull/.qgis2/python/plugins/Blurring', '/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/MacOS/../Resources/python', '/Users/jctull/.qgis2/python', '/Users/jctull/.qgis2/python/plugins', '/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/usr/local/Cellar/qgis-28/HEAD/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-3.0-osx_cocoa', '/Library/Python/2.7/site-packages', '/Users/jctull/.qgis2//python', '/Users/jctull/.qgis2/python/plugins/DigitizingTools/tools', '/Users/jctull/.qgis2/python/plugins/irods_qgis', '/Users/jctull/.qgis2/python/plugins/mmqgis/forms', '.', '/Users/jctull/.qgis2/python/plugins/SelectTools/tools', '/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/Resources/python/plugins/fTools/tools', '/Users/jctull/.qgis2/python/plugins/MetaSearch/ext-libs']

Traceback (most recent call last):
  File "/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 196, in loadPlugin
    **import**(packageName)
  File "/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/jctull/.qgis2/python/plugins/postgis_geoprocessing/__init__.py", line 28, in 
    from postgis_geoprocessing.OgrGeoprocessingProviderPlugin import \
  File "/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/jctull/.qgis2/python/plugins/postgis_geoprocessing/OgrGeoprocessingProviderPlugin.py", line 35, in 
    from postgis_geoprocessing.OgrGeoprocessingProvider import OgrGeoprocessingProvider
  File "/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/jctull/.qgis2/python/plugins/postgis_geoprocessing/OgrGeoprocessingProvider.py", line 36, in 
    from postgis_geoprocessing.distance import distance
  File "/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/jctull/.qgis2/python/plugins/postgis_geoprocessing/distance.py", line 35, in 
    from processing.core.parameters import ParameterVector
  File "/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named parameters

Python version:
2.7.9 (default, Jan 29 2015, 06:27:40) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]

QGIS version:
2.9.0-Master Master, 2481ce6

Python path: ['/Users/jctull/.qgis2/python/plugins/sextante_animove', '/Users/jctull/.qgis2/python/plugins/QSDM', '/Users/jctull/.qgis2/python/plugins/processing', '/Users/jctull/.qgis2/python/plugins/Blurring', '/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/MacOS/../Resources/python', u'/Users/jctull/.qgis2/python', u'/Users/jctull/.qgis2/python/plugins', '/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/MacOS/../Resources/python/plugins', '/usr/local/Cellar/qgis-28/HEAD/lib/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/usr/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/wx-3.0-osx_cocoa', '/Library/Python/2.7/site-packages', u'/Users/jctull/.qgis2//python', '/Users/jctull/.qgis2/python/plugins/DigitizingTools/tools', '/Users/jctull/.qgis2/python/plugins/irods_qgis', '/Users/jctull/.qgis2/python/plugins/mmqgis/forms', '.', '/Users/jctull/.qgis2/python/plugins/SelectTools/tools', '/usr/local/Cellar/qgis-28/HEAD/QGIS.app/Contents/Resources/python/plugins/fTools/tools', '/Users/jctull/.qgis2/python/plugins/MetaSearch/ext-libs']

**Comment by gioman** [comment]
Hi,
in your 

~/.qgis2/python/plugins

folder do you have any "processing" one?

**Comment by jctull** [comment]
Hi Giovanni,

Yes:

ls -al ~/.qgis2/python/plugins/processing
total 296
drwxr-xr-x   24 jctull  staff    816 Oct 20 15:19 .
drwxr-xr-x   51 jctull  staff   1734 Feb 23 11:48 ..
-rw-r--r--    1 jctull  staff   1293 Oct 20 07:49 Makefile
-rw-r--r--    1 jctull  staff   6571 Oct 20 07:49 ProcessingPlugin.py
-rw-r--r--    1 jctull  staff   6870 Oct 20 07:49 ProcessingPlugin.pyc
-rw-r--r--    1 jctull  staff   1466 Oct 20 07:49 **init**.py
-rw-r--r--    1 jctull  staff   1772 Oct 20 07:49 **init**.pyc
drwxr-xr-x   14 jctull  staff    476 Oct 20 15:19 algs
drwxr-xr-x   28 jctull  staff    952 Oct 20 15:19 core
drwxr-xr-x    6 jctull  staff    204 Oct 20 07:49 exampleprovider
drwxr-xr-x  101 jctull  staff   3434 Oct 20 07:49 gui
drwxr-xr-x   31 jctull  staff   1054 Oct 20 07:49 images
-rw-r--r--    1 jctull  staff     38 Oct 20 07:49 interface.py
-rw-r--r--    1 jctull  staff    171 Oct 20 07:49 interface.pyc
-rw-r--r--    1 jctull  staff    441 Oct 20 07:49 metadata.txt
drwxr-xr-x   49 jctull  staff   1666 Oct 20 15:19 modeler
drwxr-xr-x   24 jctull  staff    816 Oct 20 15:19 outputs
drwxr-xr-x   38 jctull  staff   1292 Oct 20 15:19 parameters
-rw-r--r--    1 jctull  staff  83075 Oct 20 07:49 resources_rc.py
-rw-r--r--    1 jctull  staff  20756 Oct 20 15:19 resources_rc.pyc
drwxr-xr-x   15 jctull  staff    510 Oct 20 15:19 script
drwxr-xr-x   20 jctull  staff    680 Oct 20 15:19 tests
drwxr-xr-x   15 jctull  staff    510 Oct 20 07:49 tools
drwxr-xr-x   28 jctull  staff    952 Oct 20 15:19 ui

**Comment by gioman** [comment]
Hi, so this mean that you are using an old Processing version (installed as a plugin update) that is masking the more recent shipped with QGIS base installation. Just remove this folder, restart QGIS and try install the plugin again.

**Comment by jctull** [comment]
Ah, thanks! Installed and loaded without issues now.
