### ISSUE TITLE
error

### ISSUE THREAD

**Issue by baditaflorin** [NaturalGIS/postgis_geoprocessing#12]
![image](https://cloud.githubusercontent.com/assets/2330999/8619653/6c5b7f34-2721-11e5-8632-bdc57489f456.png)

**Comment by gioman** [comment]
It is not an error, the output of this tools is a PostGIS layer (created in the same DB where the inputs come from). The output is not loaded automatically because Processing do not have a way to do it (yet).

**Comment by baditaflorin** [comment]
I think that would be more Useful if it would be explain also there, because if not it is confusing.
