### ISSUE TITLE
ImportError: No module named parameters

### ISSUE THREAD

**Issue by nygeog** [NaturalGIS/postgis_geoprocessing#15]
Not sure if this is the correct place to ask, but I'm having trouble installing. 

```
No module name parameters
```

![postgis_geoprocessing_error](https://cloud.githubusercontent.com/assets/2790599/8813623/ee7f0616-2fd2-11e5-96a1-47c04ad04d29.png)

**Comment by nygeog** [comment]
Not sure if this is the right place to post this but I got an error when trying to install in QGIS

No module named parameters

![postgis_geoprocessing_error](https://cloud.githubusercontent.com/assets/2790599/8813644/19e1926a-2fd3-11e5-845c-3968db463092.png)

**Comment by gioman** [comment]
Hi, Please check if in .qgis2/python/plugins/ you have a "processing" folder, if yes then delete it, restart qgis and try again. Thanks.

**Comment by nygeog** [comment]
Thanks! That did it.
