### ISSUE TITLE
The plugin won't install on windows 7 in QGIS 2.14

### ISSUE THREAD

**Issue by RegenGIS** [NaturalGIS/postgis_geoprocessing#17]
When installing the plugin on windows 7 in QGIS 2.14 I get the following error message:

Couldn't load plugin 'postgis_geoprocessing' 

ImportError: cannot import name ogrConnectionString 

I'm using the OSGeo4W installer.

**Comment by gioman** [comment]
You must ensure that you are using Processing shipped with QGIS 2.14. So delete any "processing" folder inside .qgis2/python/plugins and installation will be ok.

**Comment by RegenGIS** [comment]
Unfortunately, this doesn't solve the problem

Date: Wed, 23 Mar 2016 07:00:46 -0700

**Comment by gioman** [comment]
have you restarted qgis? do you use a custom path for qgis configurations/plugins?

**Comment by RegenGIS** [comment]
I restarted multiple times. I have a standard installation. It is on windows 7 though.

Cheers,

Mark

<div>-------- Oorspronkelijk bericht --------</div><div>Van: Giovanni Manghi <notifications@github.com> </div><div>Datum:2016-03-23  18:31  (GMT+01:00) </div><div>Aan: NaturalGIS/postgis_geoprocessing <postgis_geoprocessing@noreply.github.com> </div><div>Cc: spatialmark <mversc10@hotmail.com> </div><div>Onderwerp: Re: [postgis_geoprocessing] The plugin won't install on windows 7 in QGIS 2.14 (#17) </div><div>
</div>

have you restarted qgis? do you use a custom path for qgis configurations/plugins?

---

**Comment by gioman** [comment]
please list the content of

c:\users\yourusernamehere.qgis2\python\plugins\

**Comment by RegenGIS** [comment]
Date: Thu, 24 Mar 2016 01:40:12 -0700

**Comment by gioman** [comment]
@spatialmark no list was sent in your comment. In my previous comment there was a typo, i meant

c:\users\yourusernamehere\.qgis2\python\plugins\

**Comment by jacobscgc** [comment]
I have the same issue again with QGIS 2.18 and found that the ogrConnectionString, ogrLayerName have been moved (removing the processing folder does not solve the problem). I've created a pull-request for the fixed link, see issue #23. 

Error message:

Couldn't load plugin 'postgis_geoprocessing' 

ImportError: cannot import name ogrConnectionString 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 308, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/chris.jacobs/.qgis2/python/plugins/postgis_geoprocessing/__init__.py", line 28, in 
    from postgis_geoprocessing.OgrGeoprocessingProviderPlugin import \
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/chris.jacobs/.qgis2/python/plugins/postgis_geoprocessing/OgrGeoprocessingProviderPlugin.py", line 35, in 
    from postgis_geoprocessing.OgrGeoprocessingProvider import OgrGeoprocessingProvider
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/chris.jacobs/.qgis2/python/plugins/postgis_geoprocessing/OgrGeoprocessingProvider.py", line 36, in 
    from postgis_geoprocessing.distance import distance
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/chris.jacobs/.qgis2/python/plugins/postgis_geoprocessing/distance.py", line 48, in 
    from processing.tools.vector import ogrConnectionString, ogrLayerName
ImportError: cannot import name ogrConnectionString


Python version: 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609] 
QGIS version: 2.18.17 Las Palmas, exported 

Python Path:
/usr/share/qgis/python/plugins/processing
/usr/share/qgis/python
/home/chris.jacobs/.qgis2/python
/home/chris.jacobs/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python2.7
/usr/lib/python2.7/plat-x86_64-linux-gnu
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/local/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/PILcompat
/usr/lib/python2.7/dist-packages/gtk-2.0
/home/chris.jacobs/.qgis2//python
/usr/share/qgis/python/plugins/go2streetview
/usr/share/qgis/python/plugins/go2streetview

**Comment by gioman** [comment]
> I have the same issue again with QGIS 2.18 and found that the ogrConnectionString, ogrLayerName have been moved (removing the processing folder does not solve the problem). I've created a pull-request for the fixed link, see issue #23.

@jacobscgc check the content of

c:\users\yourusernamehere\.qgis2\python\plugins\

you must NOT have any "processing" folder there.

**Comment by jacobscgc** [comment]
@gioman , I have deleted the whole .qgis folder because that is usually the problem. I have double checked but there is nothing in the plugins directory (I'm on linux 16.04 by the way, not on windows). 
I have searched for the ogrConnectionString and ogrLayerName functions and they are not in vector.py anymore but in OgrAlgorithm.py. So that explains the error.

**Comment by gioman** [comment]
@jacobscgc 

> I have deleted the whole .qgis folder because that is usually the problem

.qgis2 as .qgis is from QGIS 1.*.



> . I have double checked but there is nothing in the plugins directory (I'm on linux 16.04 by the way, not on windows).

ok, but from your error log you have 3rd party plugins in /usr/share/qgis/python/plugins/ which is weird (but possibly unrelated). By the way I'm also on Linux.



> I have searched for the ogrConnectionString and ogrLayerName functions and they are not in vector.py anymore but in OgrAlgorithm.py. So that explains the error.

here in the python console:

`from processing.tools.vector import ogrConnectionString, ogrLayerName`

works, while

`from processing.algs.gdal.OgrAlgorithm import ogrConnectionString, ogrLayerName`

returns

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ImportError: cannot import name ogrConnectionString
```
The plugin works just fine as is now on 2.18 on both Linux and Windows, I tested on my box and as well on clean Linux/Windows testing VMs. I really don't see why to apply https://github.com/NaturalGIS/naturalgis_postgis_geoprocessing/pull/23 as it will break the plugin.

**Comment by jacobscgc** [comment]
@gioman I've discussed the issue with the system administrator and we've discovered that we were using an older version of the processing plugin (from before it became a core utility). We were using the processing version 2.10.3 instead of 2.12.19, which explains why is wasn't working. 

Thanks for your help.
