### ISSUE TITLE
cannot import name ogrConnectionString

### ISSUE THREAD

**Issue by glw** [NaturalGIS/postgis_geoprocessing#18]
Hi Im getting an error with your toolbox.

"cannot import name ogrConnectionString"

Im using Windows 7 64bit, QGIS 2.14.0

I can provide more details if needed.

Thanks!

**Comment by gioman** [comment]
see https://github.com/NaturalGIS/postgis_geoprocessing/issues/17#issuecomment-200356672

cheers!
