### ISSUE TITLE
PQconnectdb failed

### ISSUE THREAD

**Issue by jctull** [NaturalGIS/postgis_geoprocessing#2]
Testing plugin with "distance to features" algorithm, I received an error (below). My layers are both in the same postgis database, the first layer is point data, the second is multi polygon. Perhaps this is not how the algorithm is intended to be used, but the error look like a conf file issue?

Error output.log:
ERROR 1: PQconnectdb failed.
FATAL:  no pg_hba.conf entry for host "fe80::1%lo0", user "jctull", database "postgis", SSL off

FAILURE:
Unable to open datasource `PG:dbname='postgis' host=localhost port=5432 user='jctull' sslmode=disable' with the following drivers.
  -> PCIDSK
  -> PDF
  -> ESRI Shapefile
  -> MapInfo File
  -> UK .NTF
  -> OGR_SDTS
  -> S57
  -> DGN
  -> OGR_VRT
  -> REC
  -> Memory
  -> BNA
  -> CSV
  -> NAS
  -> GML
  -> GPX
  -> LIBKML
  -> KML
  -> GeoJSON
  -> Interlis 1
  -> Interlis 2
  -> OGR_GMT
  -> GPKG
  -> SQLite
  -> OGR_DODS
  -> ODBC
  -> WAsP
  -> PGeo
  -> MSSQLSpatial
  -> PostgreSQL
  -> OpenFileGDB
  -> XPlane
  -> DXF
  -> Geoconcept
  -> GeoRSS
  -> GPSTrackMaker
  -> VFK
  -> PGDUMP
  -> OSM
  -> GPSBabel
  -> SUA
  -> OpenAir
  -> OGR_PDS
  -> WFS
  -> HTF
  -> AeronavFAA
  -> Geomedia
  -> EDIGEO
  -> GFT
  -> GME
  -> SVG
  -> CouchDB
  -> Cloudant
  -> Idrisi
  -> ARCGEN
  -> SEGUKOOA
  -> SEGY
  -> XLS
  -> ODS
  -> XLSX
  -> ElasticSearch
  -> Walk
  -> CartoDB
  -> SXF
  -> Selafin
  -> JML
  -> TIGER
  -> AVCBin
  -> AVCE00
  -> HTTP

**Comment by gioman** [comment]
The first part of the message is clear, it can't connect to the DB.

ERROR 1: PQconnectdb failed.
FATAL: no pg_hba.conf entry for host "fe80::1%lo0", user "jctull", database "postgis", SSL off

The plugin was tested until now with postgis layers loaded from connections defined within qgis with all the details: host, username, password and db name.

**Comment by jctull** [comment]
These layers are loaded in the canvas through the add postgis layers menu item. My db connection does not require a password because it is locally hosted and the db is owned by my user account name.

**Comment by jctull** [comment]
Adding the password into my conf made it run, although it would be preferable to have that as an option if the db can connect without a password.
