### ISSUE TITLE
Feature Request: make db password optional

### ISSUE THREAD

**Issue by jctull** [NaturalGIS/postgis_geoprocessing#3]
For locally hosted db's, qgis is able to connect if the user credentials (username) has an admin role in the db without requiring a password. It would be ideal if the plugin could function without requiring the password being stored in the conf file in the db connection.

(Not sure how to tag this as a feature request/enhancement.)

**Comment by gioman** [comment]
I was thinking about the error message

ERROR 1: PQconnectdb failed.
FATAL: no pg_hba.conf entry for host "fe80::1%lo0", user "jctull", database "postgis", SSL off

you posted yesterday here

https://github.com/NaturalGIS/postgis_geoprocessing/issues/2

and as a matter of fact is not a plugin nor a ogr2ogr (the tools that the plugins uses to run the queries) one. The message comes from PostgreSQL.

I tested by creating, in my PostgreSQL local installation, a user with no password (--no-password) and then run a query using ogr2ogr from the command line, example

`ogr2ogr -f PostgreSQL "PG:dbname='gio2' host=localhost port=5432 user='gio2' sslmode=disable" "PG:dbname='gio2' host=localhost port=5432 user='gio2' sslmode=disable" -sql "SELECT ST_Intersection(g1.geom,g2.geom) AS geom, g1. id_0 AS id_clipper, g2. id_0 AS id_clipped FROM "public"."clipper" AS g1, "public"."toclip" AS g2 WHERE ST_Intersects(g1.geom,g2.geom) is true" -nln clipped -lco SCHEMA=public -lco FID=gid -nlt MULTIPOLYGON -lco GEOMETRY_NAME=geom --config PG_USE_COPY YES -overwrite`

and it failed with a similar message from PostgreSQL.

After modifying pg_hba.conf (changing the METHOD for my local connection from "md5" to "trust") then the above query (that you see do no uses a "password" parameter) started to work, and so does the plugin.

To me there isn't anything to fix/improve (about this specific case of course) in the plugin, please give it a try and report back.

Cheers

**Comment by gioman** [comment]
Reopen if necessary.
