### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by pcav** [NaturalGIS/postgis_geoprocessing#6]
This command::

processing.runandload("gdalogr:importvectorintopostgisdatabaseavailableconnections",0,"dbname='test'
host=test port=1523 user='georef' password='***'
estimatedmetadata=true srid=8307 type=POINT table="GEOREF"."GEO_NODI_BT"
(GEOMETRY_WGS84)
sql=",3,"EPSG:4326","","","georef","geo_node","id","None","geom",0,"","","-180.0,180.0,-90.0,90.0",False,"","",False,False,False,False,False,False,True,True,"")

returns

 SyntaxError: invalid syntax

It might be due to the quotation.  Probably processing should replace " with \" if the argument contains an " when preparing the call.

Possibly upstream.

**Comment by gioman** [comment]
This tool is not part of this plugin, is now a QGIS core tool part of the Processing gdal/ogr toolbox. If still valid a file a ticket in the qgis bug tracker.
