### ISSUE TITLE
Import creates an empty geometry without warning

### ISSUE THREAD

**Issue by pcav** [NaturalGIS/postgis_geoprocessing#7]
This command:

processing.runalg("gdalogr:importvectorintopostgisdatabaseavailableconnections",1,"/home/sample.shp",8,"EPSG:3003","","","public","c4","id","None","geom",0,"","","1554732.66406,1771665.40625,4678313.0,4924775.96094",False,"","",True,False,False,False,False,False,True,True,"")

loads a table, but empty.

**Comment by pcav** [comment]
Tested with another shp from the same folder, it works. Tried many different combinations, could not spot a difference and a reason of the failure.

**Comment by pcav** [comment]
Failing layer available if it helps.

**Comment by gioman** [comment]
This tool is not part of this plugin, is now a QGIS core tool part of the Processing gdal/ogr toolbox. If still valid a file a ticket in the qgis bug tracker.
